#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Timer_Interrupt

include $(IDF_PATH)/make/project.mk

PROJECT_VERSION := "1.0.0"

