#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := I2C_Scan

include $(IDF_PATH)/make/project.mk

PROJECT_VER="1.0.1"

